<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\Atlas.Setup.Launcher\atlas.ico</ApplicationIcon>
    <AssemblyName>Atlas.UpdateHost</AssemblyName>
    <RootNamespace>Atlas.UpdateHost</RootNamespace>
  </PropertyGroup>

</Project>
